export const arabic = {
'Skip to content':'انتقل إلى المحتوى','Sessions':'الحصص','First visit':'زيارتك الأولى','Gallery':'الصور','Find us':'موقعنا','FAQ':'أسئلة شائعة',
'RIYADH, SAUDI ARABIA':'الرياض، المملكة العربية السعودية','EST. 2024':'تأسس عام ٢٠٢٤','CEYLON':'سيلان','BADMINTON CLUB':'نادي الريشة الطائرة','Good games.':'مباريات ممتعة.','Even better company.':'وصحبة أجمل.',
'A Sri Lankan community in Riyadh, open to everyone. Find your people on court, two sessions a week.':'مجتمع سريلانكي في الرياض يرحب بالجميع. تعرّف على أصدقاء جدد في الملعب، حصتان كل أسبوع.',
'Join the club':'انضم إلى النادي','Your first session':'حصتك الأولى','All levels welcome':'جميع المستويات مرحب بها','Random doubles':'زوجي بشراكات متغيرة','ON COURT NOW':'في الملعب الآن','YOUR NEXT GAME':'مباراتك القادمة','Wednesday':'الأربعاء','Saturday':'السبت','night doubles.':'زوجي مسائي.','morning doubles.':'زوجي صباحي.','Time':'الوقت','Riyadh time':'بتوقيت الرياض','Where':'المكان','Session fee':'رسوم الحصة','Your place':'حجزك','Ask the club for the current rate':'اسأل النادي عن الرسوم الحالية','Confirm with the club before arriving':'أكد حجزك مع النادي قبل الحضور',
'Ask to join this session ↗':'اطلب الانضمام لهذه الحصة ↗','Get directions ↗':'الاتجاهات ↗','Add to calendar +':'أضف إلى التقويم +','MAKE IT A WEEKLY THING':'اجعلها عادة أسبوعية','Two sessions.':'حصتان.','One good routine.':'روتين صحي وممتع.',
'Random partners, friendly rallies, and room to improve. All times are local to Riyadh.':'شركاء متغيرون، ومباريات ودية، وفرصة للتطور. جميع المواعيد بتوقيت الرياض.','MIDWEEK RESET':'نشاط منتصف الأسبوع','WEEKEND ENERGY':'طاقة نهاية الأسبوع','Wednesday nights':'مساء الأربعاء','Saturday mornings':'صباح السبت','Join a session ↗':'انضم إلى حصة ↗','NEW HERE? YOU BELONG.':'جديد هنا؟ أهلاً بك.','Your first session,':'حصتك الأولى،','made simple.':'بكل سهولة.',
'You don’t need a partner or tournament experience. Come for a game and get to know the club.':'لا تحتاج إلى شريك أو خبرة في البطولات. تعال للعب وتعرّف على النادي.','Say hello':'تواصل معنا','Tell us your name, playing level, and preferred day. The club will confirm your place and the current fee.':'أخبرنا باسمك ومستواك واليوم المناسب لك. سيؤكد النادي حجزك والرسوم الحالية.','Pack the basics':'جهّز الأساسيات','Bring sports shoes, water, and your racket if you have one. Ask about borrowing equipment when you get in touch.':'أحضر حذاءً رياضياً وماءً ومضربك إن وجد. اسأل عن استعارة المعدات عند التواصل.','Meet us on court':'نلتقي في الملعب','Aim to arrive 10 minutes early to meet the group and warm up. We mix doubles partners so you can join in.':'احضر قبل الموعد بعشر دقائق للتعارف والإحماء. نغيّر شركاء الزوجي لتتمكن من المشاركة.','Beginners and experienced players are welcome. Bring a friend, too.':'نرحب بالمبتدئين وأصحاب الخبرة. اصطحب صديقاً أيضاً.','Let’s play ↗':'هيا نلعب ↗','THE PEOPLE. THE RALLIES. THE MEMORIES.':'الأصدقاء. المباريات. الذكريات.','This is':'هذا هو','our club.':'نادينا.','From weeknight doubles to tournament days. Real moments from the Ceylon Badminton Club community.':'من مباريات الأسبوع إلى أيام البطولات. لحظات حقيقية من مجتمع نادي سيلان للريشة الطائرة.','Loading club photos…':'جارٍ تحميل صور النادي…','Show fewer photos':'عرض صور أقل','Explore all club photos':'شاهد جميع صور النادي','FROM THE PEOPLE WHO PLAY':'من أعضاء النادي','SEE YOU ON COURT':'نراك في الملعب','Green Badminton Club.':'نادي جرين للريشة الطائرة.','Riyadh.':'الرياض.','Wednesday 8–10 PM · Saturday 8–10 AM':'الأربعاء ٨–١٠ مساءً · السبت ٨–١٠ صباحاً','Confirm your place before travelling. Open the club’s map pin for the precise location.':'أكد حجزك قبل الذهاب. افتح موقع النادي على الخريطة لمعرفة العنوان الدقيق.','View map':'عرض الخريطة','BEFORE YOU PICK UP A RACKET':'قبل أن تحمل المضرب','A few':'بعض','answers.':'الإجابات.','Contact the club for the current court contribution and first-session arrangements before you come.':'تواصل مع النادي لمعرفة المساهمة الحالية وترتيبات الحصة الأولى قبل الحضور.','Bring sports shoes, water, and a racket if you have one. If you need to borrow equipment, ask the club before your first visit.':'أحضر حذاءً رياضياً وماءً ومضرباً إن وجد. للاستعارة، اسأل النادي قبل زيارتك الأولى.','YOUR NEXT GOOD GAME STARTS HERE':'مباراتك الممتعة القادمة تبدأ هنا','Come for badminton.':'تعال للريشة الطائرة.','Stay for the people.':'وابقَ من أجل الأصدقاء.','Join the club ↗':'انضم إلى النادي ↗','Already a member?':'عضو بالفعل؟','Sign in for RSVPs, scores & rankings':'سجل الدخول للحجوزات والنتائج والتصنيف','Back to top ↑':'إلى الأعلى ↑','Directions ↗':'الاتجاهات ↗'
}
